[package]
name = "core"
version = "0.1.0"
authors = ["Hakan Akdag <hakanakdag46@gmail.com>"]
description = "Core"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
bincode = "*"
validify = { version = "*" }

[dependencies.redis]
version = "*"
